version: "2"
services:
  calculater:
    build:
      context: ./cal
      dockerfile: Dockerfile
    command: CompileDaemon -build="go install" -command="app" 
    volumes:
      - ./cal:/go/src/app
    networks:
      - rabbit-network
      - default
    external_links:
      - talk_rabbit_1:rabbit

networks:
  rabbit-network:
    external:
      name: talk_default
