version: "2"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./node_modules/.bin/nodemon server.js
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - rabbit-network
      - default
    external_links:
      - talk_rabbit_1:rabbit
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api

networks:
  rabbit-network:
    external:
      name: talk_default
