version: "2"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./node_modules/.bin/nodemon server.js
    networks:
      - rabbit-network
      - default
    volumes:
      - ./api:/app
      - /app/node_modules
    external_links:
      - talk_rabbit_1:rabbit

networks:
  rabbit-network:
    external:
      name: talk_default
